security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        # Páginas públicas
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }

        # Rutas específicas por rol
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/vehicule/new, roles: ROLE_ADMIN }
        - { path: ^/vehicule/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/vehicule/\d+$, roles: [ROLE_ADMIN, ROLE_CLIENT] }

        - { path: ^/reservation, roles: IS_AUTHENTICATED_FULLY }

        # Por defecto, acceso solo a usuarios autenticados
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10